export type WaterCheckLegalKey = "privacy" | "terms" | "health-and-ai-disclaimer" | "consumer-health-data";

export type WaterCheckLegalSection = {
  heading: string;
  paragraphs: readonly string[];
};

export type WaterCheckLegalContent = {
  eyebrow: string;
  title: string;
  footerLabel: string;
  intro: string;
  sections: readonly WaterCheckLegalSection[];
};

export const WATER_CHECK_LEGAL_CONTENT = {
  privacy: {
    eyebrow: "Product information",
    title: "Privacy",
    footerLabel: "Privacy",
    intro:
      "This notice describes the archived Water Check information pages that remain available for legal reference. It does not describe a released app, because The Water Check app is paused and is not available for public use.",
    sections: [
      {
        heading: "What this website asks you to provide",
        paragraphs: [
          "The archived Water Check pages do not provide a way to submit health information, drink or product scans, AI conversations, email addresses, accounts, age, gender, ethnicity, or racial identity. They have no waitlist, account registration, health questionnaire, symptom entry, or demographic prompt.",
          "If app work resumes, the product is intended for adults 18 and older. That 18+ statement is an eligibility rule only; these pages do not collect an age or date of birth to enforce it.",
        ],
      },
      {
        heading: "Operational website delivery",
        paragraphs: [
          "Cloudflare Pages hosts and delivers this website for Expected End LLC. When someone requests a page, Cloudflare processes operational traffic information that may include an IP address, traffic-routing data, the requested host and path, request and response headers, timestamps, system configuration, and security or network signals. Cloudflare may also derive service metrics such as request volume, errors, cache performance, availability, and threat signals.",
          "Expected End LLC uses that processing to route, cache, deliver, protect, and troubleshoot this static website. The release has no server-side Water Check function, application database, health journal, or visitor-log export. Cloudflare controls its provider-level processing under its services, privacy policy, security controls, and published retention practices.",
        ],
      },
      {
        heading: "Cookies, browser storage, analytics, and external links",
        paragraphs: [
          "The current Water Check release does not set a cookie or write to local storage or session storage. It does not include a Water Check analytics beacon, advertising pixel, payment flow, account feature, session replay, chat widget, social embed, experiment SDK, or remote font. Cloudflare adds operational caching, security, and Network Error Logging response headers but did not set a cookie in the reviewed route captures.",
          "The pages link to Instagram for optional future updates. Instagram is a separate destination and receives a request only after you choose that link; its own terms and privacy practices apply there.",
        ],
      },
      {
        heading: "What a future app may do",
        paragraphs: [
          "If app work resumes, a future experience may let adults log or scan drinks, record hydration and nutrient estimates, make later bloat check-ins, and receive educational AI-assisted explanations about possible personal patterns. None of those app inputs or outputs is collected or generated by these archived pages.",
          "Before any future app begins collecting health-related or other sensitive information, The Water Check must publish a new notice that explains the actual data, purposes, recipients, choices, safeguards, and retention practices and must obtain any consent required for the launched experience.",
        ],
      },
      {
        heading: "Future demographic information",
        paragraphs: [
          "Demographic collection is outside this website release. If a later app proposes collecting gender, ethnicity, racial identity, age, or similar information, that collection must be optional, purpose-specific, include a “prefer not to say” choice, and complete privacy and equity review before launch.",
        ],
      },
      {
        heading: "Changes and contact",
        paragraphs: [
          "Expected End LLC provides this notice effective August 8, 2026. Use the contact link above for questions about this website. This notice must be revised before the website or a future app begins a materially different information practice.",
        ],
      },
    ],
  },
  terms: {
    eyebrow: "Product information",
    title: "Terms",
    footerLabel: "Terms",
    intro:
      "These terms are written for the archived Water Check information pages. If app work resumes, any released product will need terms that match its actual experience.",
    sections: [
      {
        heading: "Eligibility and current experience",
        paragraphs: [
          "These information pages and any resumed product are intended for adults age 18 and older. The pages have no account, waitlist, health journal, scanning feature, AI conversation, or live App Store or Google Play listing.",
          "These pages provide no app-download control. They do not reserve access, create an account, submit information, or promise a release date.",
        ],
      },
      {
        heading: "Information, not medical care",
        paragraphs: [
          "Website descriptions, fictional examples, and future-feature concepts are general informational material. They are not medical advice, diagnosis, treatment, prevention, nutrition counseling, or a substitute for care from a qualified professional.",
          "Bloating and changes in how a person feels can have many causes. Nothing on this website determines body composition or identifies the definitive cause of a symptom or health condition.",
        ],
      },
      {
        heading: "Acceptable use",
        paragraphs: [
          "You may use the website for lawful personal informational purposes. You may not interfere with its operation or security, attempt unauthorized access, introduce malicious code, impersonate another person, violate another person’s rights, or use automated activity that unreasonably burdens the website.",
        ],
      },
      {
        heading: "Website materials and outside destinations",
        paragraphs: [
          "The original Water Check name, branding, text, visuals, and layout are protected by their applicable intellectual-property rights. Viewing this website does not grant permission to reproduce, sell, publish, or create derivative works from protected materials.",
          "Links may lead to services operated by others, including Instagram. The Water Check does not control those destinations, and their own terms and privacy practices apply when you visit them.",
        ],
      },
      {
        heading: "No product or release promise",
        paragraphs: [
          "The archived information pages may change. Historical or possible feature descriptions are not guarantees. No app availability, feature set, compatibility, result, release date, or uninterrupted website operation is promised.",
          "A future app is not made available under these website terms. Before launch, separate or revised terms must describe the actual app experience and any account, subscription, or data practices it uses.",
        ],
      },
      {
        heading: "Changes and contact",
        paragraphs: [
          "Expected End LLC provides these website terms effective August 8, 2026. Use the contact link above for questions. Material changes will be identified by a new effective date. These terms do not state a governing-law or venue provision.",
        ],
      },
    ],
  },
  "health-and-ai-disclaimer": {
    eyebrow: "Important limitations",
    title: "Health & AI Disclaimer",
    footerLabel: "Health & AI Disclaimer",
    intro:
      "The archived Water Check information pages provide only general product information. They do not accept health inputs, analyze a drink, produce a personal result, or provide an AI conversation.",
    sections: [
      {
        heading: "For adults and for information only",
        paragraphs: [
          "The website and planned experience are for adults age 18 and older. Website copy, fictional demonstrations, feature descriptions, and any future educational output are not professional medical or nutrition advice and are not a substitute for a qualified professional.",
        ],
      },
      {
        heading: "Limits of planned AI and nutrition estimates",
        paragraphs: [
          "A future app may use AI and available product or nutrition information to organize journal entries and suggest possible patterns. Those explanations and estimates are intended to be educational, approximate, and potentially incomplete.",
          "AI output can be incorrect, outdated, missing context, or based on uncertain inputs. It does not diagnose, treat, or prevent any condition, determine body composition, or identify the definitive cause of bloating or another health concern.",
        ],
      },
      {
        heading: "Possible patterns are not causes",
        paragraphs: [
          "A drink log followed by a later bloat check-in may help someone notice a personal sequence. Timing or repetition does not prove that a drink, ingredient, nutrient, or behavior caused the experience. Bloating can have many causes, including causes that a drink journal cannot observe.",
        ],
      },
      {
        heading: "Do not rely on the product for care decisions",
        paragraphs: [
          "Do not use this website or a future app as the only basis for starting, stopping, or changing medical care, medication, supplements, or a restrictive diet. Questions about symptoms, nutrition, or care decisions should be discussed with an appropriately qualified professional.",
          "The Water Check is not an emergency service. If you believe you may have a medical emergency, contact local emergency services rather than relying on this website or a future app.",
        ],
      },
      {
        heading: "Future product review",
        paragraphs: [
          "Before a future app is released, its actual inputs, models, data sources, output wording, error handling, and safety boundaries must be reviewed and reflected in an updated disclaimer. This page does not claim that those future implementation details have been selected or validated.",
        ],
      },
    ],
  },
  "consumer-health-data": {
    eyebrow: "Product information",
    title: "Consumer Health Data",
    footerLabel: "Consumer Health Data",
    intro:
      "This notice separates the archived Water Check information pages from health-related information a future app may handle if work resumes. It does not assert that any particular consumer-health law applies.",
    sections: [
      {
        heading: "Current website behavior",
        paragraphs: [
          "The archived Water Check pages do not provide a way to submit consumer health data, bloat or symptom check-ins, drink or product scans, hydration or nutrient logs, AI conversations, demographic details, account information, or an email address.",
          "The 18+ label describes who any resumed experience would be for. These pages do not ask for age or identity information to verify eligibility.",
        ],
      },
      {
        heading: "Operational website requests",
        paragraphs: [
          "Cloudflare Pages hosts and secures this website for Expected End LLC. Cloudflare processes operational traffic information that may include an IP address, traffic-routing data, the requested host and path, request and response headers, timestamps, system configuration, and security or network signals. It may derive service metrics used to deliver, protect, and troubleshoot the site.",
          "This operational review is separate from future app health inputs. The current website does not turn a visitor’s request information into a health journal or AI health explanation.",
        ],
      },
      {
        heading: "Possible future health-related features",
        paragraphs: [
          "If app work resumes, a future app may let an adult record drinks, scans or descriptions, hydration and nutrient estimates, bloat check-ins, and notes used to explore possible personal patterns. These are possibilities, not current collection practices.",
          "Before collection begins, a new notice must describe the actual categories collected, why they are used, who receives them, how long they are kept, what safeguards and choices exist, and how a person can use any rights that actually apply to the launched service.",
        ],
      },
      {
        heading: "Demographic information is outside this release",
        paragraphs: [
          "This website does not collect gender, ethnicity, racial identity, age, or similar demographic information. If a later app proposes those fields, they must be optional, purpose-specific, offer “prefer not to say,” and complete privacy and equity review before launch.",
        ],
      },
      {
        heading: "No current app-rights workflow",
        paragraphs: [
          "Because the app is not operating and this website has no health-data submission feature, this page does not promise a deletion portal, export tool, account dashboard, fixed response process, or app-specific retention period. An updated notice must explain any applicable request method and verified operational process before future collection starts.",
        ],
      },
      {
        heading: "Updates and contact",
        paragraphs: [
          "Expected End LLC provides this notice effective August 8, 2026. Use the contact link above for questions. It must be updated before the future app handles consumer health data or when the website begins a materially different information practice.",
        ],
      },
    ],
  },
} as const satisfies Record<WaterCheckLegalKey, WaterCheckLegalContent>;
